receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 20s
    limit_mib: 2048
    spike_limit_mib: 512

  batch:
    send_batch_size: 512
    timeout: 5s

  filter/network_metrics:
    error_mode: ignore
    metrics:
      metric:
        - 'name != "onix_http_request_count"'

  transform/beckn_ids:
    error_mode: ignore
    trace_statements:
      - set(span.attributes["_beckn_tx"], span.attributes["transaction_id"]) where span.attributes["transaction_id"] != nil
      - replace_pattern(span.attributes["_beckn_tx"], "-", "") where span.attributes["_beckn_tx"] != nil
      - set(span.trace_id, TraceID(span.attributes["_beckn_tx"])) where span.attributes["_beckn_tx"] != nil

  filter/network_traces:
    error_mode: ignore
    traces:
      span:
        - 'attributes["sender.id"] == nil'

  filter/network_logs:
    error_mode: ignore
    logs:
      log_record:
        - 'resource.attributes["eid"] != "AUDIT"'

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: onix
    const_labels:
      observability: otel-collector
      service_name: onix-ev-charging-bap

  otlp_http/collector2:
    endpoint: https://obs.prod.ubc.nbsl.org.in
    compression: gzip
    auth:
      authenticator: oauth2client

extensions:
  oauth2client:
    token_url: https://obs-auth.prod.ubc.nbsl.org.in/oauth2/token
    client_id: otel-collector-chz
    client_secret: CE2D578B-0985-4B0C-A772-3B3047539560
    endpoint_params:
      audience: otel-collector-network

  health_check:
    endpoint: 0.0.0.0:13133

  zpages:
    endpoint: 0.0.0.0:55679

service:
  telemetry:
    metrics:
      level: none

  extensions: [health_check, zpages, oauth2client]

  pipelines:
    metrics/network:
      receivers: [otlp]
      processors: [memory_limiter, filter/network_metrics, batch]
      exporters: [otlp_http/collector2, prometheus]

    traces/network:
      receivers: [otlp]
      processors: [filter/network_traces, transform/beckn_ids, batch]
      exporters: [otlp_http/collector2]

    logs/network:
      receivers: [otlp]
      processors: [filter/network_logs, batch]
      exporters: [otlp_http/collector2]